pleasebelieveme/hansabal

.gitattributes

chore: gitattributes

---

src/main/java/org/example/anonymous/common/config/CacheConfig.java
src/main/java/org/example/anonymous/common/config/QueryDslConfig.java
src/main/java/org/example/anonymous/common/config/RedisConfig.java
src/main/java/org/example/anonymous/common/config/WebConfig.java
src/main/java/org/example/anonymous/common/exception/BizException.java
src/main/java/org/example/anonymous/common/exception/CommonErrorCode.java
src/main/java/org/example/anonymous/common/exception/ErrorCode.java
src/main/java/org/example/anonymous/common/exception/ErrorResponse.java
src/main/java/org/example/anonymous/common/exception/GlobalExceptionHandler.java

[feat]: 초기 init

---

src/main/java/org/example/hansabal/domain/product/entity/CartItem.java
src/main/java/org/example/hansabal/domain/product/entity/Product.java

- close #19
-extends BaseEntity를 추가
-엔티티 부분
-

refactor: extends BaseEntity를 추가(#19)

---

src/main/java/org/example/hansabal/domain/comment/controller/CommentController.java
src/main/java/org/example/hansabal/domain/comment/dto/request/CreateCommentRequest.java
src/main/java/org/example/hansabal/domain/comment/dto/response/CommentResponse.java
src/main/java/org/example/hansabal/domain/comment/entity/Comment.java
src/main/java/org/example/hansabal/domain/comment/service/CommentService.java

- close #20 
- updateComment API
- 없음
- 없음

feat: updateComment (#20)

---

src/main/java/org/example/hansabal/domain/product/controller/ProductController.java
src/main/java/org/example/hansabal/domain/product/dto/response/ProductResponseDto.java
src/main/java/org/example/hansabal/domain/product/service/ProductService.java

- close #25
-refactor: response dto의 static factory 변경
- dto와 dto 사용하는 부분 from 사용하게 변경
-

refactor: response dto의 static factory 변경(#25)

---

src/main/java/org/example/hansabal/domain/users/entity/User.java

refactor: user_update (User엔티티 updateUser변경)

---

src/main/java/org/example/hansabal/domain/users/dto/request/UserCreateRequest.java
src/main/java/org/example/hansabal/domain/users/entity/User.java

- close #67 
- User엔티티 유니크처리
- UserRole @NotNull
-
-

refactor: User엔티티 유니크 처리, UserRole @Notnull

---

src/main/java/org/example/hansabal/common/jwt/JwtFilter.java
src/main/java/org/example/hansabal/common/jwt/JwtUtil.java
src/main/java/org/example/hansabal/domain/auth/service/AuthService.java

- close #
- 리프레쉬 토큰 구현한 것이 사라져 있어서 다시 푸쉬~
-
-

refactor: 리프레쉬 토큰 구현한거 dev에서 사라져 있어서 다시 푸쉬

---

src/main/java/org/example/hansabal/domain/product/controller/ProductController.java
src/main/java/org/example/hansabal/domain/product/repository/CartItemRepository.java
src/main/java/org/example/hansabal/domain/product/repository/ProductRepository.java
src/main/java/org/example/hansabal/domain/product/repository/ProductRepositoryCustom.java
src/main/java/org/example/hansabal/domain/product/repository/ProductRepositoryImpl.java
src/main/java/org/example/hansabal/domain/product/service/ProductService.java

- close #77
-
페이징 구현및 수정
-contorller service 변경 imp추가
repository 추가 생성 
-

Refactor/productpage 구현 (#77)

---

src/main/java/org/example/hansabal/domain/product/dto/response/ProductResponseDto.java
src/main/java/org/example/hansabal/domain/product/repository/ProductRepositoryImpl.java

- close #92
- productId -> id
-product dto ,repository
-

refactor: 퀴리 수정및 productid 없애기

---

src/main/java/org/example/hansabal/domain/trade/entity/Requests.java
src/main/java/org/example/hansabal/domain/trade/entity/Trade.java
src/main/java/org/example/hansabal/domain/trade/repository/RequestsRepository.java
src/main/java/org/example/hansabal/domain/trade/repository/TradeRepository.java
src/main/java/org/example/hansabal/domain/trade/service/RequestsService.java
src/main/java/org/example/hansabal/domain/trade/service/TradeService.java

- 86#
- PK이름 통일화
- PK이름 id로 변경(trade, requests)
-

refac : PK id로 통일

---

src/test/java/org/example/hansabal/domain/dib/service/integration/DibTest.java

test: dibService test modifying

---

src/main/java/org/example/hansabal/domain/wallet/repository/WalletHistoryRepository.java

- none#
- WalletHistoryRepository 잘못된 부분 수정
- countquery 수정
-

chore : countQuery 수정

---

src/main/java/org/example/hansabal/domain/comment/repository/CommentRepositoryImpl.java

fix: findByBoardId where 절

---

src/main/java/org/example/hansabal/domain/product/exception/ProductErrorCode.java
src/main/java/org/example/hansabal/domain/product/service/ShopSearchService.java

- close #138 
-private-> public 변경
-test에서 값을 읽어올려하는데 불가능해서 변경
-

refactor: public으로 변경

---

src/main/java/org/example/hansabal/common/exception/BizException.java
src/main/java/org/example/hansabal/common/exception/CommonErrorCode.java
src/main/java/org/example/hansabal/common/exception/ErrorCode.java
src/main/java/org/example/hansabal/common/exception/ErrorResponse.java

fix: 이셉션 반환값 변경

---

src/main/java/org/example/hansabal/domain/users/entity/User.java
src/test/java/org/example/hansabal/board/BoardServiceTest.java
src/test/java/org/example/hansabal/domain/comment/integration/controller/CommentControllerTest.java
src/test/java/org/example/hansabal/domain/comment/integration/service/CommentTest.java
src/test/java/org/example/hansabal/domain/comment/unit/CommentUnitTest.java
src/test/java/org/example/hansabal/domain/dib/integration/service/DibTest.java

- close #156 
- 댓글 유닛 테스트 작성 해봤습니다. 사실 할 필요 없다고 생각하는데 (이미 통합테스트로 서비스단 테스트 코드는 작성 되어있음) Mock 객체랑 given,ReflectionTestUtils 같은 것들 어떻게 활용할지 이런거 궁금해 하실거 같아서 추가 해둡니다. 기존 통합 테스트로 짜던 서비스 테스트랑 거의 비슷하기 때문에 크게 달라지지 않았습니다.
- 추가로 Controller 테스트용 클래스를 만들어두기만 했습니다.
- 하는김에 User쪽 생성자도 하나 추가해뒀으니 참고 바랍니다~
-

feat: comment unit test

---

src/main/java/org/example/hansabal/domain/users/repository/UserRepository.java
src/main/java/org/example/hansabal/domain/users/service/UserService.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserTest.java

- close #158 
- close #160 
- close #162 
- close #163 
- close #164 
- close #165 
- close #166 
- close #167 
- close #170 
- close #171 
- close #172 
- close #174 
- 비밀번호 암호화테스트 생성
- UserRole 테스트 필요성 제거
- 회원조회시 isDeleted칼럼값이 true이면 예외처리
- 유저생성기능에 추가
-
테스트 코드가 완료되었고
머지한 후에 BeforeEach 적용 후에 다시 pr올리도록 하겠습니다.

feat: 유저 테스트코드

---

src/main/resources/comment_user_test_db.sql
src/main/resources/user_test_db.sql
src/test/java/org/example/hansabal/domain/users/service/integration/UserTest.java

fix: 테스트환경 수정

---

src/test/java/org/example/hansabal/domain/comment/integration/controller/CommentControllerTest.java

- close #193 
- 댓글 생성 컨트롤러 Vaildation 에러 테스트입니다.
-
-

test: create comment controller vaildattion error test

---

src/main/java/org/example/hansabal/domain/users/entity/User.java
src/main/java/org/example/hansabal/domain/users/entity/UserRole.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserTest.java

- close #180 
- close #181 
-
-
-

refactor: 유저서비스 테스트코드 100% 달성!

---

src/main/java/org/example/hansabal/domain/users/repository/RedisRepository.java
src/main/resources/user_test_db.sql
src/test/java/org/example/hansabal/domain/auth/service/integration/AuthTest.java

- close #183 
- close #184 
- close #186 
- close #187 
- close #188
- close #189  
- close #190 
- close #191 
- close #192  
- 어스 테스트
-
-

feat: auth 테스트 코드

---

src/main/resources/requests_test_db.sql
src/main/resources/trade_test_db.sql

- close #
- .sql 파일들 수정
- +baseEntity 값들 추가
-

fix : test requests 수정

---

src/main/java/org/example/hansabal/domain/review/service/ReviewService.java
src/main/resources/review_test_db.sql
src/main/resources/review_user_test_db.sql
src/test/java/org/example/hansabal/domain/review/service/ReviewServiceMockTest.java
src/test/java/org/example/hansabal/domain/review/service/ReviewServiceTest.java

- close #211 
- 리뷰 생성, 예외 테스트 코드 작성 (모키토 -> 통합으로 변경했습니다.)
- test.sql 파일 작성(일단 주석처리 해놨습니다.)
- 서비스 단에서 @Valid 제거하였습니다. 
-
-

feat : 리뷰 test

---

src/test/java/org/example/hansabal/domain/auth/service/unit/AuthErrorCodeTest.java
src/test/java/org/example/hansabal/domain/users/service/unit/RedisRepositoryTest.java
src/test/java/org/example/hansabal/domain/users/service/unit/UserErrorCodeTest.java

- close #214 
- close #216 
- close #217 
- 커버리지를 높이기 위해 굳이 작성한 테스트 코드
-
-

feat: 유저, 어스 테스트 코드

---

src/main/java/org/example/hansabal/domain/users/controller/UserController.java
src/main/java/org/example/hansabal/domain/users/entity/UserRole.java
src/test/java/org/example/hansabal/domain/auth/controller/AuthControllerTest.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserControllerTest.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserServiceTest.java
src/test/java/org/example/hansabal/domain/users/service/unit/QUserTest.java

- close #219
- close #221 
- close #222 
- close #223 
- close #224 
- 추후에 변수명 통일, 주석정리, 코드정리할 예정
-
-

feat: 어스 컨트롤러 테스트 코드 작성

---

build.gradle
src/main/java/org/example/hansabal/common/config/SwaggerConfig.java
src/main/java/org/example/hansabal/common/jwt/SecurityUrlMatcher.java
src/main/java/org/example/hansabal/domain/auth/controller/AuthController.java
src/main/java/org/example/hansabal/domain/auth/dto/request/LoginRequest.java
src/main/java/org/example/hansabal/domain/auth/dto/response/TokenResponse.java
src/main/java/org/example/hansabal/domain/users/controller/UserController.java
src/main/java/org/example/hansabal/domain/users/dto/request/UserCreateRequest.java
src/main/java/org/example/hansabal/domain/users/dto/request/UserUpdateRequest.java
src/main/java/org/example/hansabal/domain/users/dto/response/UserResponse.java

- close #229 
- close #234 
- close #235 
- close #236 
- close #237  
- close #238 
- close #239 
- close #240 
-
-
- 스웨거 적용
- 서버 실행후 http://localhost:8080/swagger-ui/index.html 로 요청
- 참고자료 https://baby9235.tistory.com/133

feat: 스웨거 적용

---

src/main/java/org/example/hansabal/domain/chat/controller/ChatController.java
src/main/java/org/example/hansabal/domain/chat/dto/response/ChatMessageSimpleResponse.java
src/main/java/org/example/hansabal/domain/chat/entity/Chat.java
src/main/java/org/example/hansabal/domain/chat/repository/ChatRepository.java
src/main/java/org/example/hansabal/domain/chat/repository/ChatRepositoryCustom.java
src/main/java/org/example/hansabal/domain/chat/repository/ChatRepositoryImpl.java
src/main/java/org/example/hansabal/domain/chat/service/ChatService.java

- close #253 
- 실시간 채팅 조회 API 입니다. 최대한 성능을 끌어올리기 위해서 Slice와 QueryDSL Projection을 활용했습니다. 이후 커서 기반 페이징이란 걸 도입해볼 예정입니다(고도화 작업 때).
-
-

feat: find chat and QueryDSL

---

src/main/java/org/example/hansabal/domain/auth/service/AuthService.java
src/main/java/org/example/hansabal/domain/users/entity/User.java
src/main/java/org/example/hansabal/domain/users/entity/UserStatus.java
src/main/java/org/example/hansabal/domain/users/exception/UserErrorCode.java
src/main/java/org/example/hansabal/domain/users/repository/UserRepository.java
src/main/java/org/example/hansabal/domain/users/scheduler/DormantUserScheduler.java
src/main/resources/user_test_db.sql
src/test/java/org/example/hansabal/domain/auth/service/integration/AuthTest.java
src/test/java/org/example/hansabal/domain/auth/service/unit/AuthUnitTest.java
src/test/java/org/example/hansabal/domain/users/service/integration/DormantUserSchedulerTest.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserServiceTest.java

- close #252 
- close #257 
- close #259 
- close #262 
- close #263 
- close #264 
- 로그인 시 계정 상태 확인
- 로그인 성공시 토큰발급 전에 로그인기록 DB에 저장
- user_status, last_login_at 추가
```
CREATE TABLE users (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(50) NOT NULL ,
password VARCHAR(100) NOT NULL ,
name VARCHAR(20) NOT NULL ,
nickname VARCHAR(20) NOT NULL ,
user_role VARCHAR(20) NOT NULL,
user_status VARCHAR(20) NOT NULL,
created_at DATETIME(6),
updated_at DATETIME(6),
deleted_at DATETIME(6),
last_login_at DATETIME(6)
) ENGINE=InnoDB;
-- password: !Aa123456
INSERT INTO users (id, email, password, name, nickname, user_role, user_status, created_at, updated_at, deleted_at, last_login_at)
VALUES (1,'test@email.com','$2a$10$KSlx0SYrksH0u7ePgjALXuojnoawGXcngfyWgAwNiTu69GLgr01Gq','testname','testn …
```

feat: 휴면계정 스케줄러 작성

---

src/main/java/org/example/hansabal/domain/payment/controller/PaymentController.java
src/main/java/org/example/hansabal/domain/payment/service/PaymentService.java
src/main/java/org/example/hansabal/domain/users/service/UserService.java
src/main/java/org/example/hansabal/domain/wallet/controller/WalletController.java
src/main/java/org/example/hansabal/domain/wallet/service/WalletHistoryService.java
src/main/java/org/example/hansabal/domain/wallet/service/WalletService.java

- none#
-다른 컨트롤러/서비스를 거치지 않고 바로 메일서비스 테스트 가능하도록 임시용 연결 테스트 메서드 작성. 
-추후 정상작동이 확인되면 삭제예정
-
- 메일서비스로 직통으로 연결되는 메서드 추가(프론트테스트 및 기능 연결 확인용)

ADD : 메일서비스 프론트테스트용 메서드 추가

---

src/main/java/org/example/hansabal/domain/wallet/repository/WalletRepository.java

refactor : repository 쿼리문 수정

---

src/main/java/org/example/hansabal/domain/payment/service/PaymentService.java

- close #308 
- 메일서비스 메서드 이름 수정으로 인한 payment 서비스쪽에 메서드 변경
-
-

fix : 메일서비스 메서드 이름 수정

---

src/main/java/org/example/hansabal/domain/review/controller/ReviewController.java
src/main/java/org/example/hansabal/domain/review/dto/response/ReviewSimpleResponse.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewCustomRepository.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewRepository.java
src/main/java/org/example/hansabal/domain/review/service/ReviewService.java

- close #315 
- 페이징 고도화 작업 및 이메일서비스 리펙토링
-
-

Feat/  리뷰페이징 고도화 작업 및 이메일 서비스 리펙토리

---

src/main/java/org/example/hansabal/domain/users/service/UserService.java
src/main/resources/templates/paymentMail.html

feat: 회원가입 완료 이메일 보내기 기능 추가

---

src/main/java/org/example/hansabal/domain/payment/service/PaymentService.java
src/main/java/org/example/hansabal/domain/wallet/controller/WalletController.java
src/main/java/org/example/hansabal/domain/wallet/exception/WalletErrorCode.java
src/main/java/org/example/hansabal/domain/wallet/service/WalletHistoryService.java
src/main/java/org/example/hansabal/domain/wallet/service/WalletService.java

엔티티 필드명 변경에 따른 수정사항
- close #
-
- getUserId->getUser, userId(user)->user(user)
-

refactor : wallet변경 관련 수정

---

src/main/java/org/example/hansabal/domain/board/service/BoardService.java

- close #
-feat : BoardSerivce 캐싱 적용
-
-

feat : BoardSerivce 캐싱 적용

---

src/main/java/org/example/hansabal/common/hibernate/FULLTEXT_MATCH_functionContributor.java
src/main/java/org/example/hansabal/domain/trade/exception/TradeErrorCode.java
src/main/java/org/example/hansabal/domain/trade/repository/RequestsRepositoryImpl.java
src/main/java/org/example/hansabal/domain/trade/repository/TradeRepositoryCustom.java
src/main/java/org/example/hansabal/domain/trade/repository/TradeRepositoryImpl.java
src/main/java/org/example/hansabal/domain/trade/service/TradeService.java
src/main/resources/index.sql
src/main/resources/services/org.hibernate.boot.model.FunctionContributor
src/test/java/org/example/hansabal/domain/trade/intergration/service/TradeServiceTest.java

- close #
- fulltext-index적용
- index생성용 index.sql추가
- querydsl 일부 변경
- fulltext-index 지원, match(?) against(? in boolean mode)
- boolean 검색 연산자 지원(+ - * ~ "")

refactor : trade

---

src/main/java/org/example/hansabal/domain/review/exception/ReviewErrorCode.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/org/example/hansabal/domain/review/service/ReviewService.java
src/test/java/org/example/hansabal/domain/review/controller/ReviewControllerTest.java

- close #364 
- 리뷰 조회 캐싱 구현
-
-

Feat/refactor v1 리뷰조회 캐싱 구현

---

infra/docker-compose.yml
src/main/java/org/example/hansabal/common/config/QueryDslConfig.java
src/main/java/org/example/hansabal/domain/board/controller/BoardController.java
src/main/java/org/example/hansabal/domain/board/dto/response/BoardPageResponse.java
src/main/java/org/example/hansabal/domain/board/repository/BoardRepositoryCustomImpl.java
src/main/resources/board_test_db.sql
src/main/resources/index.sql
src/test/java/org/example/hansabal/config/JsonConfig.java
src/test/java/org/example/hansabal/domain/board/controller/BoardControllerTest.java

- close #
-FULLTEXTINDEX 적용
-FULLTEXTINDEX 적용
-

refactor : FULLTEXTINDEX 적용

---

infra/docker-compose.yml
src/main/java/org/example/hansabal/common/config/QueryDslConfig.java
src/main/java/org/example/hansabal/domain/board/controller/BoardController.java
src/main/java/org/example/hansabal/domain/board/dto/response/BoardPageResponse.java
src/main/java/org/example/hansabal/domain/board/repository/BoardRepositoryCustomImpl.java
src/main/resources/board_test_db.sql
src/main/resources/index.sql
src/test/java/org/example/hansabal/config/JsonConfig.java
src/test/java/org/example/hansabal/domain/board/controller/BoardControllerTest.java

- close #
-boardcontroller 테스트 코드 작성
-
-

Fix/boardcontroller 테스트 코드 작성

---

.gitignore
infra/Dockerfile
infra/docker-compose.yml
infra/prometheus/config/prometheus.yml
src/main/java/org/example/hansabal/common/jwt/SecurityUrlMatcher.java

- close #367 
- close #368 
- close #369 
- close #371 
- close #372 
-
-
-

feat: mysql, redis, springboot 모니터링, springboot(로컬 -> 도커컨테이너)

---

src/main/java/org/example/hansabal/common/config/SecurityConfig.java
src/main/java/org/example/hansabal/common/jwt/SecurityUrlMatcher.java

- close #375 
- close #377 
-
-
-

fix: 스웨거 url 수정, SecurityConfig url 정리

---

infra/docker-compose.yml
src/main/java/org/example/hansabal/common/config/FullTextIndexInitializer.java
src/main/resources/application.yml
src/main/resources/index.sql

fix: ci/cd

---

src/main/java/org/example/hansabal/domain/review/controller/ReviewController.java
src/main/java/org/example/hansabal/domain/review/dto/request/CreateReviewRequest.java
src/main/java/org/example/hansabal/domain/review/dto/request/UpdateReviewRequest.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewCustomRepositoryImpl.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewRepository.java
src/main/java/org/example/hansabal/domain/users/entity/User.java
src/test/java/org/example/hansabal/domain/review/controller/ReviewControllerTest.java
src/test/java/org/example/hansabal/domain/review/service/ReviewServiceTest.java
src/test/resources/review_product_test_db.sql
src/test/resources/review_user_test_db.sql

- close #391 
- product 엔티티에서 user맵핑으로 인해 sql파일에서 외래키 추가
-  final 필드 사용 문제로 인해 역직렬화를 지원하지 못해서 dto단에 @JsonProperty를 추가
- 테이블명 users -> user로 변경으로 인해 sql파일에서 수정
- import 쪽에 안쓰는 기능들(회색처리된곳들) 삭제
- 
-

fix : 리뷰 테스트통과를 위한 수정

---

src/test/resources/comment_user_test_db.sql

refactor: user-> users

---

src/main/java/org/example/hansabal/common/jwt/SecurityUrlMatcher.java

fix: 이메일 URL 시큐리티처리

---

src/main/java/org/example/hansabal/domain/users/service/UserService.java
src/test/java/org/example/hansabal/domain/users/service/integration/UserServiceTest.java

- close #225 
- close #411 
-
-
-

fix: 이메일 중복 예외 테스트 수정

---

src/main/java/org/example/hansabal/domain/product/controller/ProductController.java
src/main/java/org/example/hansabal/domain/product/dto/request/ProductRequestDto.java
src/main/java/org/example/hansabal/domain/product/entity/Product.java
src/main/java/org/example/hansabal/domain/product/service/ProductService.java

refactor: user 삭제

---

src/main/java/org/example/hansabal/domain/product/repository/ProductRepository.java

refactor: 삭제

---

src/main/java/org/example/hansabal/domain/board/dto/response/BoardSimpleResponse.java
src/main/java/org/example/hansabal/domain/board/service/TestDataInitService.java
src/test/java/org/example/hansabal/domain/board/BoardServiceUtillTest.java
src/test/java/org/example/hansabal/domain/trade/intergration/service/TradeServiceTest.java

fix: board test

---

src/main/java/org/example/hansabal/domain/review/controller/ReviewController.java
src/main/java/org/example/hansabal/domain/review/dto/response/ReviewPageResult.java
src/main/java/org/example/hansabal/domain/review/dto/response/ReviewSimpleResponse.java
src/main/java/org/example/hansabal/domain/review/repository/ReviewRepository.java
src/main/java/org/example/hansabal/domain/review/service/ReviewService.java

리뷰 페이징 테스트 수정

---

.github/workflows/cd.yml

fix: cd에서 테스트코드 수행 안하고 빠르게 배포

---

.github/workflows/cd.yml

feat: 배포테스트1
- close #431 
- close #432 
-
-
-

fix: cd.yml에서 docker 설치

---

.github/workflows/cd.yml

fix: cd.yml 수정

---

.github/workflows/cd.yml

fix: cd.yml 수정2

---

.github/workflows/cd.yml

fix: cd.yml 수정4

---

.github/workflows/ci.yml

fix: ci.yml S3연결로 변경

---

src/main/java/org/example/hansabal/domain/product/repository/CartRepository.java

refactor: 오류수정

---

src/main/java/org/example/hansabal/domain/product/dto/response/ItemResponse.java

refactor: item productId로 받아오게 변경

---

.github/workflows/cd.yml
.github/workflows/ci.yml

fix: ci.yml, cd.yml 이름 수정

---

src/main/java/org/example/hansabal/domain/product/controller/CartItemController.java

refactor: @AuthenticationPrincipal추가
